import { useState, useEffect, useRef, useCallback } from 'react';
import { socket } from '../services/socket.js';

const RTC_CONFIG = {
    iceServers: [
        { urls: 'stun:stun.l.google.com:19302' },
        { urls: 'stun:stun1.l.google.com:19302' },
        { urls: 'stun:stun2.l.google.com:19302' }
    ]
};

/**
 * Custom Hook: WebRTC Peer Connection & Signaling Lifecycle
 * @param {MediaStream|null} localStream 
 * @param {string|null} roomId 
 */
export const useWebRTC = (localStream, roomId) => {
    const [remoteStream, setRemoteStream] = useState(null);
    const [connectionState, setConnectionState] = useState('disconnected'); // disconnected | connecting | connected | failed
    const [partnerSocketId, setPartnerSocketId] = useState(null);

    const peerConnectionRef = useRef(null);
    const localStreamRef = useRef(localStream);
    localStreamRef.current = localStream;

    // Clean up peer connection
    const cleanupPeerConnection = useCallback(() => {
        if (peerConnectionRef.current) {
            peerConnectionRef.current.onicecandidate = null;
            peerConnectionRef.current.ontrack = null;
            peerConnectionRef.current.onconnectionstatechange = null;
            peerConnectionRef.current.close();
            peerConnectionRef.current = null;
        }
        setRemoteStream(null);
        setConnectionState('disconnected');
    }, []);

    // Create RTCPeerConnection instance
    const createPeerConnection = useCallback((targetSocketId) => {
        cleanupPeerConnection();

        const pc = new RTCPeerConnection(RTC_CONFIG);
        peerConnectionRef.current = pc;
        setPartnerSocketId(targetSocketId);

        // Add local tracks to peer connection
        if (localStreamRef.current) {
            localStreamRef.current.getTracks().forEach(track => {
                pc.addTrack(track, localStreamRef.current);
            });
        }

        // Handle remote stream tracks
        pc.ontrack = (event) => {
            console.log('[WebRTC] Received remote stream track:', event.streams[0]);
            if (event.streams && event.streams[0]) {
                setRemoteStream(event.streams[0]);
            }
        };

        // Handle ICE candidates generated by browser
        pc.onicecandidate = (event) => {
            if (event.candidate && targetSocketId) {
                socket.emit('ice-candidate', {
                    roomId,
                    targetSocketId,
                    candidate: event.candidate
                });
            }
        };

        // Monitor connection state
        pc.onconnectionstatechange = () => {
            console.log('[WebRTC] Peer Connection State:', pc.connectionState);
            setConnectionState(pc.connectionState);
        };

        return pc;
    }, [cleanupPeerConnection, roomId]);

    // Initiator creates Offer
    const initiateOffer = useCallback(async (targetSocketId) => {
        try {
            console.log('[WebRTC] Initiating offer to target socket:', targetSocketId);
            const pc = createPeerConnection(targetSocketId);
            setConnectionState('connecting');

            const offer = await pc.createOffer();
            await pc.setLocalDescription(offer);

            socket.emit('offer', {
                roomId,
                targetSocketId,
                offer
            });
        } catch (err) {
            console.error('[WebRTC] Error initiating offer:', err);
            setConnectionState('failed');
        }
    }, [createPeerConnection, roomId]);

    // Setup Socket.IO WebRTC signaling listeners
    useEffect(() => {
        if (!roomId) return;

        // Peer joined: as the room host/existing member, initiate offer
        const handlePeerJoined = ({ socketId }) => {
            console.log('[WebRTC] Peer joined room, starting offer negotiation:', socketId);
            initiateOffer(socketId);
        };

        // Receive Offer: create answer
        const handleOffer = async ({ senderSocketId, offer }) => {
            console.log('[WebRTC] Received offer from:', senderSocketId);
            try {
                const pc = createPeerConnection(senderSocketId);
                setConnectionState('connecting');

                await pc.setRemoteDescription(new RTCSessionDescription(offer));
                const answer = await pc.createAnswer();
                await pc.setLocalDescription(answer);

                socket.emit('answer', {
                    roomId,
                    targetSocketId: senderSocketId,
                    answer
                });
            } catch (err) {
                console.error('[WebRTC] Error processing offer:', err);
                setConnectionState('failed');
            }
        };

        // Receive Answer: set remote description
        const handleAnswer = async ({ senderSocketId, answer }) => {
            console.log('[WebRTC] Received answer from:', senderSocketId);
            const pc = peerConnectionRef.current;
            if (pc) {
                try {
                    await pc.setRemoteDescription(new RTCSessionDescription(answer));
                } catch (err) {
                    console.error('[WebRTC] Error setting remote answer:', err);
                }
            }
        };

        // Receive ICE Candidate
        const handleIceCandidate = async ({ candidate }) => {
            const pc = peerConnectionRef.current;
            if (pc && candidate) {
                try {
                    await pc.addIceCandidate(new RTCIceCandidate(candidate));
                } catch (err) {
                    console.error('[WebRTC] Error adding ICE candidate:', err);
                }
            }
        };

        // Peer Left
        const handlePeerLeft = () => {
            console.log('[WebRTC] Peer left room');
            cleanupPeerConnection();
        };

        socket.on('peer-joined', handlePeerJoined);
        socket.on('offer', handleOffer);
        socket.on('answer', handleAnswer);
        socket.on('ice-candidate', handleIceCandidate);
        socket.on('peer-left', handlePeerLeft);

        return () => {
            socket.off('peer-joined', handlePeerJoined);
            socket.off('offer', handleOffer);
            socket.off('answer', handleAnswer);
            socket.off('ice-candidate', handleIceCandidate);
            socket.off('peer-left', handlePeerLeft);
        };
    }, [roomId, initiateOffer, createPeerConnection, cleanupPeerConnection]);

    // Clean up on unmount or room leave
    useEffect(() => {
        return () => {
            cleanupPeerConnection();
        };
    }, [cleanupPeerConnection]);

    return {
        remoteStream,
        connectionState,
        partnerSocketId,
        cleanupPeerConnection
    };
};
